url: "https://andrejplatonow.github.io"
baseurl: "/unendlichkeitsfiktion"
repository: unendlichkeitsfiktion/andrejplatonow.github.io
title: Unendlichkeitsfiktion
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: custom
permalink: "/:categories/:title/"
paginate: "10"
paginate_path: "/page:num/"
timezone: "DE"
locale: "de-DE"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  bio: Blogroll
  links:
  - label: Buddenbohm
    icon: fas fa-fw fa-link
    url: https://www.buddenbohm-und-soehne.de/
  - label: Wieselblog
    icon: fas fa-fw fa-link
    url: https://wieselblog.wordpress.com/
footer:
  links: []
atom_feed:
  hide: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    comments: true
    read_time: false
    show_date: true
    share: false
    related: false
    header:
      image: "/assets/images/error-420-XDa7EBHFzlo-unsplash.jpg"
      image_description: A description of the image
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
date_format: "%d.%m.%Y"
