---
title: Unendlichkeitsfiktion
minimal_mistakes_skin: dirt
search: true
repository: unendlichkeitsfiktion/andrejplatonow.github.io
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: "10"
paginate_path: "/page:num/"
timezone: 
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  bio: Blogroll
  links:
  - label: Wieselblog
    icon: fas fa-fw fa-link
    url: https://wieselblog.wordpress.com/
  - label: Buddenbohm
    icon: fas fa-fw fa-link
    url: https://www.buddenbohm-und-soehne.de/
footer:
  links: []
atom_feed:
  hide: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: true
    share: false
    related: false
    show_date: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
date_format: "%d.%m.%Y"
