---
url: https://unendlichkeitsfiktion.de
repository: unendlichkeitsfiktion/andrejplatonow.github.io
title: Unendlichkeitsfiktion
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: custom
permalink: "/:categories/:title/"
paginate: "20"
paginate_path: "/page:num/"
timezone: DE
locale: de-DE
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: "Admin"
author_profile: false
footer:
  links: []
atom_feed:
  hide: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: false
    sidebar:
      nav: "blogroll"
    comments: true
    read_time: false
    show_date: true
    share: false
    related: false
    header:
      image: "/assets/images/mond.jpg"
      imagehome: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
    sidebar:
      nav: "blogroll"    
    comments: false
    read_time: false
    show_date: false
    share: false
    related: false
    header:
      image: "/assets/images/mond.jpg"
      imagehome: true
date_format: "%d.%m.%Y"
comments:
  provider: custom
compress_html:
  clippings: all
  ignore:
    envs: development
incremental: true
