---
url: https://unendlichkeitsfiktion.de
repository: unendlichkeitsfiktion/andrejplatonow.github.io
title: Unendlichkeitsfiktion
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: custom
permalink: "/:categories/:title/"
paginate: "20"
paginate_path: "/page:num/"
timezone: DE
locale: de-DE
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  bio: Blogroll
  links:
  - label: Au fil des mots
    icon: ''
    url: http://aufildesmots.biz/
  - label: Buddenbohm
    icon: ''
    url: https://www.buddenbohm-und-soehne.de/
  - label: Goncourt
    icon: ''
    url: http://goncourt.net/Blog/
  - label: Hotel
    icon: ''
    url: http://hotelmama.it/
  - label: Istrici
    icon: ''
    url: https://istrici.wordpress.com/
  - label: Kraulquappe
    icon: ''
    url: https://kraulquappe.com/
  - label: Kreuzberg
    icon: ''
    url: https://kreuzbergsuedost.wordpress.com/
  - label: Landleben
    icon: ''
    url: https://landlebenblog.org/blog/
  - label: Mequito
    icon: ''
    url: http://mequito.org/
  - label: Ricarda Kiel
    icon: ''
    url: https://www.ricardakiel.de/hier-ist-etwas-ein-brief/
  - label: Wald und Höhle
    icon: ''
    url: https://waldundhoehle.wordpress.com/
  - label: Wieselblog
    icon: ''
    url: https://wieselblog.wordpress.com/
footer:
  links: []
atom_feed:
  hide: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    sidebar:
      nav: "blogroll"
    comments: true
    read_time: false
    show_date: true
    share: false
    related: false
    header:
      image: "/assets/images/mond.jpg"
      imagehome: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
    sidebar:
      nav: "blogroll"    
    comments: false
    read_time: false
    show_date: false
    share: false
    related: false
    header:
      image: "/assets/images/mond.jpg"
      imagehome: true
date_format: "%d.%m.%Y"
comments:
  provider: custom
compress_html:
  clippings: all
  ignore:
    envs: development
incremental: true
